In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
                 )

In [3]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [6]:
df.Name

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2     Bonnell, Miss Elizabeth
Name: Name, dtype: str

# df['Name'
]

# df['Name']

In [7]:
a=df['Name']

In [8]:
a

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2     Bonnell, Miss Elizabeth
Name: Name, dtype: str

# df["Name"]

In [9]:
a = df["Name"]

In [10]:
a

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2     Bonnell, Miss Elizabeth
Name: Name, dtype: str

#

# df.describe()

In [5]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

In [2]:
df

NameError: name 'df' is not defined

# a= df.Name

In [7]:
a

NameError: name 'a' is not defined

In [8]:
a = df["Name"]

In [9]:
a

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2     Bonnell, Miss Elizabeth
Name: Name, dtype: str

In [10]:
a.values()

TypeError: 'StringArray' object is not callable

In [11]:
a.values

<StringArray>
[ 'Braund, Mr. Owen Harris', 'Allen, Mr. William Henry',
  'Bonnell, Miss Elizabeth']
Length: 3, dtype: str

In [12]:
df.Age.values

array([22, 35, 58])

In [4]:
df.describe().values

array([[ 3.        ],
       [38.33333333],
       [18.23001189],
       [22.        ],
       [28.5       ],
       [35.        ],
       [46.5       ],
       [58.        ]])

In [5]:
df.tail()

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [6]:
df.tail(1)

                      Name  Age     Sex
2  Bonnell, Miss Elizabeth   58  female

In [7]:
df.Name.shape

(3,)

In [8]:
df[df.Age>30]

                       Name  Age     Sex
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [9]:
df.notna()

   Name   Age   Sex
0  True  True  True
1  True  True  True
2  True  True  True

In [4]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [5]:
df.value_counts()

Name                      Age  Sex
Braund, Mr. Owen Harris   22   male      1
Allen, Mr. William Henry  35   male      1
Bonnell, Miss Elizabeth   58   female    1
Name: count, dtype: int64

In [6]:
df.Age.value_counts()

Age
22    1
35    1
58    1
Name: count, dtype: int64

In [8]:
df.count()

Name    3
Age     3
Sex     3
dtype: int64

In [9]:
df.Age.count()

np.int64(3)